version: "3.8"

services:
  web:
    container_name: web
    build: ./docker/web
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - ./frontend:/app
    tty: true
    stdin_open: true
    command: /bin/sh
